const fs = require('fs');

const портретLocations = [
  {n:"Угол с выбеленным кирпичом",po:["Прислонилась к кирпичной стене","Сидит у основания стены","Стоит вполоборота к стене","Рукой касается кирпича","Смотрит вдоль стены"],bg:"A corner of an interior wall with whitewashed exposed brick — the rough texture catching the light unevenly. The mortar between bricks is old and crumbling in places. A warm, slightly grainy backdrop with real depth and character."},
  {n:"Подоконник с лёгким тюлем",po:["Сидит на подоконнике, тюль за спиной","Держит край тюля в руке","Смотрит сквозь тюль на свет","Облокотилась на раму окна","Стоит рядом, ткань касается плеча"],bg:"A wide windowsill with a sheer linen curtain drifting slightly in the draught. The light comes through soft and diffused. The sill itself is painted white, slightly chipped. Outside is indistinct — just pale light and the suggestion of sky."},
  {n:"Стена с облупившейся краской",po:["Стоит у стены, смотрит в камеру","Прислонилась затылком к стене","Рукой касается слоёв краски","Сидит на полу у стены","Смотрит вбок, стена в фокусе"],bg:"A section of interior wall where several layers of old paint are peeling back — pale green beneath cream beneath white. The peeling reveals a kind of geology of the room's history. Beautiful and imperfect."},
  {n:"Угол с арочным нишем",po:["Стоит в нише арки","Сидит в нише, ноги вытянуты","Выглядывает из ниши","Облокотилась на край арки","Прислонилась к стене внутри ниши"],bg:"A small arched niche set into a thick wall — plastered smooth inside, with a shallow shelf at the base. The arch frames the subject perfectly. The wall is very white and the depth of the niche creates strong shadow on the sides."},
  {n:"Угол с тёмным бархатным занавесом",po:["Держит край занавеса","Выглядывает из-за занавеса","Прислонилась к занавесу","Сидит у основания занавеса","Обернулась, занавес за плечом"],bg:"A deep bottle-green velvet curtain hanging against a pale wall — the fabric heavy and richly textured, gathering in dense folds at the base. The contrast between the dark curtain and the light wall creates a dramatic, theatrical backdrop."},
  {n:"Оштукатуренная стена с трещинами",po:["Стоит вплотную к стене","Рукой прослеживает трещину","Прислонилась щекой к стене","Сидит у стены на корточках","Смотрит в камеру, стена близко"],bg:"An old plastered wall with a network of fine hairline cracks spreading like a map. The plaster is the colour of aged paper — warm, creamy, not quite white. The texture reads beautifully in raking light."},
  {n:"Световое пятно от окна на полу",po:["Стоит в световом пятне","Сидит в квадрате света","Смотрит вниз на свет","Рукой касается края светового пятна","Лежит в луче света"],bg:"A pool of warm afternoon sunlight falling through a window onto old wooden floorboards — the light rectangle precise and warm against the darker surrounding floor. The light moves almost imperceptibly. A quiet, fleeting moment of natural beauty."},
  {n:"Угол с плетёной ширмой",po:["Стоит перед ширмой","Выглядывает из-за ширмы","Держит край ширмы","Прислонилась к ширме","Сидит у основания ширмы"],bg:"A rattan room divider screen in warm honey tones — the woven pattern casting gentle grid shadows on the wall and floor. Behind the screen the room is slightly out of focus. The material is natural and imperfect."},
  {n:"Угол у потёртого деревянного стула",po:["Сидит верхом на стуле","Стоит за стулом, руки на спинке","Сидит боком на стуле","Облокотилась на спинку стула","Стоит рядом, держит спинку"],bg:"A single worn wooden chair placed against a plain wall — the paint rubbed away at the armrests and seat edge, the legs scuffed. The chair has a quiet, stubborn presence. The wall behind is a simple matte tone."},
  {n:"Угол у каминной полки без огня",po:["Стоит у каминной полки","Облокотилась локтем на полку","Сидит перед каминным порталом","Рукой касается мраморной полки","Смотрит в пустой камин"],bg:"An old fireplace surround — the mantelpiece marble, veined and cool, the firebox dark and empty. The surround is ornate but modest in scale. The tiles inside the firebox are Victorian, patterned in blue. No fire, but the structure holds warmth in its shape."},
  {n:"Угол с голой лампочкой на шнуре",po:["Стоит под лампой","Смотрит на лампу","Держит шнур лампочки","Сидит под источником света","Лицо в свете голой лампочки"],bg:"A bare Edison bulb hanging on a long braided cord from a high ceiling — the filament visible and warm amber. The bulb illuminates a small halo. The surrounding wall and ceiling fade into shadow. Intimate industrial simplicity."},
  {n:"Угол с книгами на полу",po:["Сидит среди стопок книг","Листает книгу, сидя на полу","Держит книгу, смотрит в камеру","Выбирает книгу из стопки","Облокотилась спиной о книжную стопку"],bg:"A corner where stacks of books have accumulated on the floor — paperbacks and hardcovers in towers of varying height. The spines face different directions. The floor is bare wood. The light is quiet and reading-room dim."},
  {n:"Угол с деревянными балками потолка",po:["Стоит под балкой","Облокотилась рукой о балку","Смотрит вверх на балки","Сидит под балочным потолком","Прислонилась к опорной балке"],bg:"The corner of a room with old exposed wooden ceiling beams — dark oak, slightly rough, crossing the low ceiling. The plaster between the beams is white. The whole space feels old, solid, and rural in the best sense."},
  {n:"Угол у высокого плинтуса",po:["Сидит у плинтуса на полу","Прислонилась к стене выше плинтуса","Стоит вплотную к стене","Рукой касается деревянного плинтуса","Смотрит вдоль плинтуса"],bg:"A wall with an unusually tall painted wooden skirting board — the kind found in old apartments. The paint is cream, slightly yellowed. The floor is parquet. The horizontal line of the skirting divides the composition beautifully."},
  {n:"Угол с розовой штукатурной стеной",po:["Прислонилась к розовой стене","Стоит перед стеной, смотрит в камеру","Рукой касается штукатурки","Сидит у стены на полу","Смотрит вбок на фоне стены"],bg:"A section of interior wall plastered in a natural clay render — the colour is a dusty, warm rose-pink from the mineral pigment. The texture is slightly rough and uneven. The light catches the imperfections beautifully."},
  {n:"Угол за полупрозрачной занавеской",po:["Стоит за полупрозрачной занавеской","Выглядывает из-за занавески","Держит край занавески, смотрит в камеру","Лицо сквозь ткань на просвет","Обернулась, занавеска падает с плеча"],bg:"A sheer white cotton curtain hanging in a doorway or window opening — the light behind it making it glow softly. The subject is barely visible through the fabric, or emerging from behind it. A dreamy, soft-focus effect created by the lightest of barriers."},
  {n:"Угол у старого сундука",po:["Сидит на сундуке","Облокотилась на крышку сундука","Стоит рядом, рука на сундуке","Открывает крышку сундука","Прислонилась к сундуку"],bg:"An old wooden chest or trunk with iron fittings — the wood darkened with age, the brass lock oxidised green. It sits against a pale wall. A solid, quiet object with the suggestion of things stored and kept."},
  {n:"Угол у кованой решётки",po:["Держит прутья решётки","Смотрит сквозь решётку","Прислонилась к решётке","Стоит рядом с решёткой","Рукой касается завитков ковки"],bg:"A decorative wrought iron grille set in a wall or door — the iron painted black, the curlicues and scrollwork typical of old European craftwork. The grille casts shadow patterns on the surrounding plaster. Beautiful geometric shadows."},
  {n:"Угол у сводчатого потолка",po:["Стоит под сводом","Смотрит вверх на свод","Руки вдоль тела, смотрит в камеру","Прислонилась к стене под сводом","Сидит у стены, свод виден над головой"],bg:"A low vaulted ceiling — plastered, whitewashed, the curve of the vault meeting the wall in a gentle arc. The space feels intimate and historical. The light is even and soft, bouncing from the curved ceiling down to the subject."},
  {n:"Угол у старой половицы",po:["Сидит на половицах, скрестив ноги","Лежит на полу, смотрит в камеру","Стоит босиком на досках","Смотрит вниз на пол","Сидит на корточках, рука на полу"],bg:"The corner of a room with original wide floorboards — the wood old, dark, the boards slightly uneven. One board near the corner is wider than the rest. The grain is visible and the finish is wax, not varnish. The floor feels genuinely old and honest."},
  {n:"Угол у вешалки с одеждой",po:["Стоит у вешалки","Перебирает одежду на вешалке","Снимает пальто с крючка","Прислонилась к вешалке","Смотрит в камеру, одежда за спиной"],bg:"A coat rack or wardrobe rail visible in a corner — a few garments hanging: a wool coat, a linen jacket, a scarf looped over a hook. The shapes are soft and layered. The clothes hint at a life without spelling it out."},
  {n:"Угол с длинным зеркалом без рамы",po:["Смотрит в зеркало, камера видит отражение","Стоит вполоборота к зеркалу","Прислонилась к стене у зеркала","Держит руку у поверхности зеркала","Отражение в зеркале, настоящая она — профиль"],bg:"A tall mirror leaning against a wall without a frame — the glass edge just visible, the reflection showing a different angle of the room. The room seen in reflection is slightly distorted, slightly other. A quiet doubling of space."},
  {n:"Угол с цементной плиткой на полу",po:["Стоит на узорчатой плитке","Сидит на плитке, смотрит в камеру","Ноги крупно — плитка фон","Стоит босиком на плитке","Смотрит вниз на узор"],bg:"The corner of a room with original encaustic cement floor tiles — geometric pattern in terracotta, cream, and sage green. The tiles are worn smooth in the centre of each by decades of footfall. The pattern is orderly but the wear gives it life."},
  {n:"Угол у чугунного радиатора",po:["Облокотилась на радиатор","Сидит на подоконнике над радиатором","Ноги на уровне радиатора — тепло","Стоит рядом, рукой касается секций","Прислонилась к стене у радиатора"],bg:"An old cast iron radiator against a white wall — the kind with ornate sectional ribs, painted cream or white, slightly chipped. The wall above is faintly discoloured from years of warmth. The radiator is solid and beautiful in its utility."},
  {n:"Угол с нишей для телефона",po:["Сидит в нише","Стоит в нише, руки по бокам","Смотрит из ниши","Прислонилась к боковой стенке ниши","Заглядывает в нишу"],bg:"A small rectangular niche set into a wall — the kind originally built to house a telephone. The niche is shallow, the plaster inside painted a different shade. The opening is just wide enough to frame a face or a figure. A quiet architectural accident."},
  {n:"Угол у старых жалюзи",po:["Смотрит сквозь жалюзи","Руки на ламелях жалюзи","Свет сквозь полосы на лице","Прислонилась к раме с жалюзи","Смотрит в камеру в полосатом свете"],bg:"Wooden venetian blinds in a window — the slats slightly warped with age, the cord yellowed. The light coming through creates horizontal stripes that fall across whatever surface is below. The effect is graphic and warm."},
  {n:"Угол с узким высоким окном",po:["Стоит у узкого окна","Смотрит в высокое окно","Прислонилась к раме","Сидит на полу у окна","Смотрит в камеру, свет сбоку"],bg:"A tall, narrow window — the kind set deep in a thick wall, the reveals visible. The glass is old and slightly uneven. The light comes in as a single bright column. The wall on either side of the window is thick and plain."},
  {n:"Угол с мозаичным полом",po:["Стоит на мозаичном полу","Сидит на мозаике","Смотрит вниз на узор","Крупно: ноги и мозаичный фон","Босиком на старой мозаике"],bg:"The corner of a hallway or bathroom with original Victorian or Art Nouveau mosaic floor tiles — tiny pieces in black, white, and occasionally cream, making a geometric pattern. The grout is old and grey. The pattern continues wall to wall without interruption."},
  {n:"Угол с хлопковым гамаком",po:["Лежит в гамаке","Сидит в гамаке","Выглядывает из гамака","Облокотилась на гамак","Встаёт из гамака"],bg:"A hand-woven cotton hammock strung across a corner or between two hooks in a room — the fabric cream or natural, the fringe hanging loose. The hammock swings slightly and the ropes cast gentle shadows on the wall. The room behind is simple."},
  {n:"Угол у старого умывальника",po:["Стоит у умывальника","Рукой касается кранов","Смотрит в маленькое зеркало над умывальником","Облокотилась на умывальник","Смотрит в камеру, умывальник рядом"],bg:"A small old wall-mounted basin — porcelain, slightly stained, with separate hot and cold taps in chrome or ceramic. The wall tiles around it are white, grouted in grey. The basin is purely functional and perfectly itself."},
  {n:"Угол у потолочной лепнины",po:["Стоит, лепнина видна над головой","Смотрит вверх на лепнину","Облокотилась о стену под лепниной","Рукой указывает на лепнину","Сидит на полу, лепнина в кадре"],bg:"The corner of a ceiling where ornate plaster moulding meets the wall — the cornice running around the room junction, with egg-and-dart or acanthus detail. The plaster is white, slightly yellowed. The ceiling decoration is the most beautiful thing in the room."},
  {n:"Угол у перевёрнутого ящика",po:["Сидит на деревянном ящике","Стоит, нога на ящике","Облокотилась на ящик","Ставит что-то на ящик","Смотрит в камеру, ящик у ног"],bg:"A plain wooden crate turned upside down as a makeshift stool or table — the kind used for produce or storage. The wood is rough and stencilled with faint lettering. It sits against a bare wall. Practical and incidentally photogenic."},
  {n:"Угол у заколоченного окна",po:["Стоит у заколоченного окна","Рукой касается досок","Смотрит в щель между досками","Прислонилась к оконной раме","Освещена светом из щели"],bg:"A window that has been roughly boarded over from the inside — the boards old and grey, light slipping through the gaps in bright lines. The frame of the original window is still visible around the boards. The light from the cracks is dramatic and directional."},
  {n:"Угол с латунными крючками",po:["Вешает что-то на крючок","Стоит у крючков","Облокотилась под крючками","Смотрит в камеру, крючки рядом","Держит предмет, снятый с крючка"],bg:"A row of old brass hooks on a simple wooden rail mounted on a pale wall — the brass patinated to a dark honey colour, the hooks curved and solid. From one hangs a straw hat. The others are bare. A small, deliberate domestic arrangement."},
  {n:"Угол у стеклянной перегородки",po:["Стоит у стеклянной перегородки","Смотрит сквозь стекло","Прислонилась к раме перегородки","Рукой касается стекла","Отражение в перегородке"],bg:"An internal glazed partition — industrial steel frame with clear glass panes. The frame is black or dark grey. Through the glass the next room is visible but blurred. The reflections on the glass surface add a layer of depth to the image."},
  {n:"Угол у деревянных ставней",po:["Стоит у ставен","Открывает ставни","Свет сквозь щели ставней","Прислонилась к закрытым ставням","Смотрит в камеру, ставни за спиной"],bg:"Solid wooden shutters in a window — painted in a faded dark blue or forest green, the slats letting thin lines of light through. The paint is old and peeling at the corners. The shutters give the room a sheltered, interior feeling even when slightly open."},
  {n:"Угол у гипсовой скульптуры",po:["Стоит рядом со скульптурой","Смотрит на скульптуру","Рядом со скульптурой, смотрит в камеру","Рукой касается гипсовой поверхности","Профиль напротив профиля скульптуры"],bg:"A plaster cast of a classical head or torso placed against a plain wall — the white of the plaster luminous in soft light. The cast is slightly dusty, a few small chips at the edges. The wall behind is neutral. The juxtaposition of faces is quietly interesting."},
  {n:"Угол у обоев в полоску",po:["Стоит на фоне полосатых обоев","Прислонилась к стене","Смотрит в камеру, обои ритмично за спиной","Сидит у стены с обоями","Рукой касается обоев"],bg:"A section of wall papered in thin vertical stripes — cream and pale sage, the pattern quiet and orderly. The paper is old and slightly loose at one corner. The stripe pattern creates a vertical rhythm behind the subject."},
  {n:"Угол с подсветкой снизу",po:["Стоит над источником подсветки","Смотрит вниз на свет","Освещена снизу вверх","Руки в луче нижнего света","Профиль в нижней подсветке"],bg:"A corner where light comes from below — a floor lamp, a strip of LED near the skirting, or a candle on the floor. The upward light reverses the usual direction of illumination, creating shadow where the face normally has light. Dramatic and unusual."},
  {n:"Угол у откидной форточки",po:["Смотрит в форточку","Открывает форточку","Свет из форточки на лице","Прислонилась к оконной раме под форточкой","Стоит, рука на форточке"],bg:"The top section of a window where a small hinged ventilation pane is open — the pane at an angle, the outside just visible. The light from outside is direct and clear. The frame is painted white, slightly aged. A small domestic gesture full of ordinary life."},
  {n:"Угол у переполненной вешалки",po:["Стоит у переполненной вешалки","Выбирает вещь на вешалке","Ищет что-то в одежде","Смотрит в камеру, вещи за спиной","Достаёт пальто с вешалки"],bg:"A coat hook near a door that has accumulated far more than it was designed for — scarves, bags, coats, a hat perched on top, an umbrella hooked over everything. The wall behind is marked from years of contact. Beautiful chaotic abundance."},
  {n:"Угол у треснувшего зеркала",po:["Смотрит в треснувшее зеркало","Профиль у трещины в зеркале","Рукой касается края трещины","Отражение в разбитом зеркале","Смотрит в камеру, трещина за ней"],bg:"A mirror with a single crack running from one corner almost to the centre — the fracture clean and precise. Both sides of the crack reflect the room slightly differently. The frame of the mirror is simple and dark. The crack is the most interesting thing in the composition."},
  {n:"Угол у дощатой стены",po:["Прислонилась к дощатой стене","Стоит перед стеной из досок","Рукой касается шероховатых досок","Сидит у дощатой стены","Смотрит в камеру, доски за спиной"],bg:"An interior wall clad in vertical tongue-and-groove planks — old pine, unpainted, the grain dark with age and slightly silvery. The knots in the wood are prominent. The surface is rough to the touch. This is an attic or outbuilding that has been made into a room."},
  {n:"Угол у стеклянного шара",po:["Держит стеклянный шар","Смотрит в шар","Шар на полке рядом","Отражение лица в шаре","Рукой придерживает шар"],bg:"A large clear glass sphere sitting on a small stand or shelf against a plain wall. The sphere reflects a distorted, wide-angle version of the room around it. The light refracts through it in small rainbow fragments. A beautiful and strange optical object."},
  {n:"Угол у открытой балконной двери",po:["Стоит в проёме балконной двери","Облокотилась на раму двери","Смотрит наружу с балкона","Свет снаружи выделяет силуэт","Прислонилась к косяку двери"],bg:"An open glass balcony door — the frame painted white, the light outside brighter than the room. The subject is in the doorway between interior and exterior. The room behind is dim and intimate. The outside is overexposed and indistinct. A threshold moment."},
  {n:"Угол у выкрашенного потолка",po:["Смотрит вверх на крашеный потолок","Лежит на полу, кадр снизу","Стоит под необычным потолком","Освещена отражённым светом с потолка","Голова вблизи окрашенной поверхности"],bg:"A ceiling painted in an unexpected colour — deep terracotta, or dusty blue-grey — making the room feel enclosed and cosy rather than open. The colour is warm and the light that bounces from it tints everything below. The walls are white or neutral."},
  {n:"Угол у кованого канделябра",po:["Стоит у канделябра","Держит свечу","Освещена свечным светом","Смотрит на пламя свечей","Профиль в мерцающем свете"],bg:"A wrought iron candelabra holding several lit candles — the iron dark, the wax dripped and accumulated around each holder. The candle light is warm and slightly unsteady, creating a flickering illumination that moves gently. The wall behind catches the warm light."},
  {n:"Угол у кружевной скатерти",po:["Облокотилась на стол с кружевом","Рукой касается кружева","Сидит у стола с кружевной скатертью","Смотрит в камеру, кружево на переднем плане","Держит край кружева"],bg:"The corner of a table covered with a white lace tablecloth — the lace old, handmade, intricate, the pattern botanical. The table is dark wood beneath. The lace overhangs the edge. The room behind is simple. The cloth is the centrepiece."},
  {n:"Угол у полки с посудой",po:["Стоит у полки с посудой","Достаёт чашку с полки","Рассматривает тарелки","Смотрит в камеру, посуда за спиной","Держит чашку"],bg:"An open kitchen shelf with mismatched ceramics — stacked plates, different mugs, a jug. The pieces are all slightly different but all belong. The shelf is wooden, the wall behind it white tile or plaster. The arrangement is practical and incidentally lovely."},
  {n:"Угол у лестничных перил",po:["Держится за перила","Прислонилась к перилам","Сидит на ступени, рука на перилах","Смотрит вниз через перила","Стоит на лестнице, перила рядом"],bg:"The corner where a staircase banister meets the landing — old turned wood, painted white or stained dark. The balusters cast repeating shadows on the wall behind. Looking through the balusters you can see the stairs going down below."}
];

const домLocations = [
  {n:"Полка с аптечными флаконами",po:["Рассматривает флаконы","Держит флакон","Переставляет флаконы","Стоит у полки, смотрит в камеру","Берёт флакон с полки"],bg:"A shelf lined with old pharmacy bottles and jars — dark amber glass, clear glass, some with original labels. The bottles hold dried herbs, oils, things collected. The light through the glass is warm and botanical. The shelf itself is narrow and wooden."},
  {n:"Угол прихожей с зеркалом и полочкой",po:["Смотрит в зеркало прихожей","Поправляет волосы у зеркала","Стоит у полочки","Держит что-то с полочки","Оглядывается у зеркала"],bg:"The narrow hallway corner with a small mirror and a shelf below it — the mirror oval, frame dark wood, the shelf holding keys, a small plant, coins. The wallpaper behind is a faded pattern. The light is dim, from further inside the apartment."},
  {n:"Кухонный угол у специй",po:["Рассматривает специи","Нюхает специю из банки","Отбирает специю для готовки","Стоит у полки со специями, смотрит в камеру","Ставит банку со специей на место"],bg:"A kitchen corner where a collection of spice jars is stored — glass jars and tins, hand-labelled, some faded. The range of colours through the glass: turmeric yellow, paprika red, cumin brown. The shelf or counter below is scarred from use."},
  {n:"Угол у детских рисунков на холодильнике",po:["Смотрит на рисунки","Добавляет рисунок на холодильник","Облокотилась на холодильник","Смотрит в камеру, рисунки за ней","Рукой касается одного из рисунков"],bg:"The side or front of a refrigerator covered in children's drawings held by fridge magnets — the drawings dense and overlapping, crayon and felt-tip, various ages and subjects. Behind this small gallery is just a white appliance."},
  {n:"Угол у кровати с кружкой",po:["Сидит на краю кровати","Держит кружку, сидя у кровати","Лежит на кровати, смотрит в камеру","Тянется за кружкой на тумбе","Встаёт с кровати"],bg:"The bedside corner — the edge of a bed, a small table or just the floor, and a mug sitting there. The mug might have a half-drunk tea in it. The bedding is rumpled. The light is morning soft. An entirely private and ordinary moment."},
  {n:"Угол у раковины с мылом",po:["Моет руки","Смотрит в зеркало у раковины","Облокотилась на раковину","Стоит у раковины, смотрит в камеру","Берёт мыло"],bg:"A bathroom basin corner — the basin small and white, a bar of soap on the edge leaving a pale residue on the porcelain. The tap is chrome and old. The wall tile behind is white with grey grout. Everything clean in a lived-in way."},
  {n:"Угол у сушилки для белья",po:["Вешает бельё на сушилку","Снимает бельё","Стоит у сушилки, смотрит в камеру","Разбирает вещи у сушилки","Облокотилась на сушилку"],bg:"A laundry drying rack in a corner of the home — cotton clothes and linens hanging, some slightly askew, the fabric soft and clean. The light is indirect, coming from a nearby window. The whole corner smells of clean washing and air."},
  {n:"Угол у домашней аптечки",po:["Открывает аптечку","Ищет что-то в аптечке","Стоит у аптечки на стене","Смотрит в камеру, аптечка рядом","Достаёт что-то из аптечки"],bg:"A wall-mounted medicine cabinet — the door ajar, showing the shelves inside with small bottles, plasters, thermometer. The cabinet is old metal or wood, painted white. The wall around it is simple. This is the most domestic of corners."},
  {n:"Подоконник с вязанием",po:["Вяжет у окна","Держит спицы","Смотрит в окно, вязание в руках","Разматывает клубок","Смотрит в камеру, вязание на коленях"],bg:"A windowsill corner where someone has left their knitting — needles still in the work, a ball of wool unspooling onto the seat. The light from the window is the reading kind. The chair or bench below is worn comfortable."},
  {n:"Угол у пианино",po:["Сидит за пианино","Играет на пианино","Кладёт руки на клавиши","Смотрит на ноты","Стоит у пианино, смотрит в камеру"],bg:"The corner of a room occupied by an upright piano — the wood dark and slightly dusty, the keys yellow with age. Sheet music on the stand. The top of the piano holds framed photographs and a small vase. The instrument is played but not polished."},
  {n:"Угол у коллекции пластинок",po:["Перебирает пластинки","Достаёт пластинку","Смотрит на обложку пластинки","Ставит пластинку на проигрыватель","Сидит у коллекции пластинок"],bg:"A corner where vinyl records are stored — in a wooden crate or on a dedicated shelf, spines facing outward. The sleeves are varied: some bright, some faded, all different decades. Nearby perhaps a turntable, or just the records themselves."},
  {n:"Угол у старой швейной машинки",po:["Сидит у швейной машинки","Шьёт на машинке","Рассматривает машинку","Рукой касается колеса машинки","Стоит у машинки, смотрит в камеру"],bg:"An old treadle or vintage electric sewing machine in a corner — the metal body in cream or black, the needle in position above the presser foot. Scraps of fabric nearby, thread on the bobbin. A completely purposeful and beautiful old machine."},
  {n:"Угол у кухонной доски с ножами",po:["Берёт нож с доски","Ставит нож на место","Стоит у доски, смотрит в камеру","Рассматривает ножи","Облокотилась у кухонной стены"],bg:"A kitchen wall where a magnetic knife strip holds a collection of knives — the blades catching the light at different angles, the handles a mix of wood and metal from different eras of the kitchen's life. The wall behind is tiled or painted."},
  {n:"Угол у батареи с сохнущими носками",po:["Вешает носки на батарею","Снимает высохший носок","Смотрит в камеру у батареи","Облокотилась на подоконник над батареей","Садится на пол у батареи"],bg:"A radiator in a corner with a few socks hanging over the top to dry — the domesticity completely unguarded. The paint on the radiator is slightly chipped. The wall above is plain. This is exactly what real apartments look like."},
  {n:"Угол у старого будильника",po:["Смотрит на будильник","Заводит будильник","Держит будильник","Лежит, будильник на тумбе рядом","Ставит будильник"],bg:"A small analog alarm clock on a bedside surface — old, round, chrome or painted, the hands at some quiet hour. The tick is audible. The surface beneath it has a pale ring from years of being in the same position. Small, faithful, old."},
  {n:"Угол у рабочего верстака",po:["Работает за верстаком","Облокотилась на верстак","Рассматривает инструменты","Стоит у верстака, смотрит в камеру","Держит инструмент"],bg:"A corner workbench — the surface scarred from years of work, scattered with small tools, a vice at one end, wood shavings in the corners. The wall behind has a pegboard with tools hanging in rough order. This is where things get made and fixed."},
  {n:"Угол у домашней библиотеки на полу",po:["Сидит среди книг","Выбирает книгу","Читает на полу","Складывает книги в стопку","Смотрит в камеру, книги вокруг"],bg:"Books on the floor of a room — not stacked neatly but living there, some open, some face-down, some in small piles. The floor is bare wood. This is a room where books are used, not displayed. The accumulation has its own order."},
  {n:"Угол у кошачьей лежанки",po:["Сидит у кошачьей лежанки","Гладит кошку на лежанке","Смотрит в камеру у кошачьего уголка","Сидит на полу рядом с лежанкой","Кладёт руку на лежанку"],bg:"A corner occupied by a cat bed or basket — the bed worn and moulded to the shape of its habitual occupant. Cat hair on the blanket. A toy nearby. The wall and floor around show the small signs of long feline habitation."},
  {n:"Угол у фотографий на стене",po:["Смотрит на фотографии","Рассматривает одну фотографию","Стоит перед стеной с фото","Смотрит в камеру, фотографии за ней","Указывает на фотографию"],bg:"A section of wall covered in framed or pinned photographs — personal photos, not art prints. Family, friends, places. Some black and white, some colour, different sizes and frames. An accumulation of life arranged on a wall over many years."},
  {n:"Угол у кофемолки",po:["Мелет кофе в кофемолке","Вдыхает аромат молотого кофе","Держит кофемолку","Насыпает кофе","Стоит у кофемолки, смотрит в камеру"],bg:"A small corner of the kitchen where coffee preparation happens — a hand grinder or small electric grinder, a bag of coffee beans, perhaps a small scale. The surface is dusted with fine coffee grounds. The smell is part of the place."},
  {n:"Угол у связки сухих трав",po:["Нюхает сухие травы","Рассматривает связки трав","Вешает пучок трав","Держит пучок трав","Стоит у связок трав, смотрит в камеру"],bg:"Bunches of dried herbs hanging from a hook or beam — lavender, rosemary, chamomile, some combination. The colours are faded but present: silver, brown, pale purple. The herbs are dry and crisp and faintly fragrant. A beautiful, practical, and old-fashioned corner."},
  {n:"Угол у открытого чемодана",po:["Разбирает чемодан","Складывает вещи в чемодан","Сидит на краю кровати у чемодана","Смотрит в камеру у открытого чемодана","Держит вещь из чемодана"],bg:"An open suitcase on the floor or bed — not yet packed or just unpacked, the interior showing the small objects of a trip. A guidebook, some rolled clothes, a charger cable. The chaos of arrival or anticipation of departure."},
  {n:"Угол у зеркала в ванной с паром",po:["Смотрит в запотевшее зеркало","Вытирает зеркало рукой","Рисует на запотевшем зеркале","Смотрит в камеру, зеркало в паре","Профиль у зеркала"],bg:"A bathroom mirror after a hot shower — completely fogged with steam, only the edges clear. The room behind is hazy with moisture. The light is diffused. A finger drawing might be visible on the glass surface. Soft, warm, private."},
  {n:"Угол у старой табуретки на кухне",po:["Сидит на табуретке","Стоит рядом с табуреткой","Ставит ногу на табуретку","Облокотилась на табуретку","Крутится на табуретке"],bg:"An old wooden stool in the kitchen — three-legged or four, the seat worn smooth from decades of use, the legs painted in a colour long faded. It lives in the corner and serves as a step, a seat, and a surface as needed."},
  {n:"Угол у шкафа с постельным",po:["Достаёт бельё из шкафа","Складывает бельё","Обнимает стопку сложенного белья","Стоит у открытого шкафа","Смотрит в камеру, шкаф открыт"],bg:"An open linen cupboard — shelves of folded bedding, towels in a neat or approximate stack, the smell of clean fabric and perhaps lavender sachets. The inside of the cupboard is a faded colour. A glimpse into the domestic order of a home."},
  {n:"Угол у цветка в горшке на полу",po:["Рассматривает большой цветок","Поливает растение","Сидит рядом с большим растением","Смотрит в камеру, растение рядом","Рукой касается листа"],bg:"A large potted plant on the floor in a corner — a monstera, a fiddle-leaf fig, or a rubber plant. The leaves are large and green and slightly dusty. The pot is terracotta or ceramic. The plant has been there long enough to reach toward the window on its own."},
  {n:"Угол у открытого окна с котом",po:["Стоит у окна рядом с котом","Гладит кота на подоконнике","Смотрит в окно вместе с котом","Смотрит в камеру, кот на подоконнике","Кот трётся о её ногу у окна"],bg:"A window with a cat sitting on the sill — the outside visible beyond, the light bright. The cat is settled and confident. The window frame is old and painted, the sill wide enough for the cat and perhaps a small plant. An entirely ordinary and entirely perfect domestic scene."},
  {n:"Угол у стола с лекарствами",po:["Разбирает лекарства","Смотрит на упаковку лекарства","Ставит лекарство на стол","Сидит у стола с лекарствами","Смотрит в камеру"],bg:"A corner of a table or bedside surface where medicine lives — a few blister packs, a bottle, perhaps a glass of water. The arrangement is temporary and practical. It speaks of illness or management of health, quietly and without drama."},
  {n:"Угол у окна в дождь",po:["Смотрит в дождливое окно","Рукой касается мокрого стекла","Дышит на стекло","Сидит у окна в дождь","Облокотилась на подоконник, дождь снаружи"],bg:"A window with rain falling outside — the glass running with rivulets of water, the world beyond dissolved into movement and grey. The inside is dry and warm. The contrast between interior comfort and exterior weather is the whole point."},
  {n:"Угол у маленького торшера",po:["Читает у торшера","Включает торшер","Смотрит в камеру в свете торшера","Сидит в кружке света от торшера","Рукой касается абажура"],bg:"A small floor lamp in a corner — a simple shade, perhaps fabric or paper, casting a warm circle of light on the area immediately below. The rest of the room is darker. The lamp is old and the shade slightly warped. The light it gives is reading-warm."},
  {n:"Угол у домашнего алтаря",po:["Стоит у домашнего алтаря","Зажигает свечу","Смотрит на предметы алтаря","Рукой касается предмета","Смотрит в камеру у алтаря"],bg:"A small personal shrine or altar in a domestic corner — candles, a few objects of significance, perhaps a photograph, a stone, a dried flower. It might be religious or entirely personal. The arrangement is deliberate and quiet."},
  {n:"Угол у самодельного стеллажа",po:["Рассматривает полки самодельного стеллажа","Достаёт предмет с полки","Ставит что-то на полку","Облокотилась на стеллаж","Смотрит в камеру у полок"],bg:"A corner bookshelf made from planks and bricks or crates — not bought but assembled. The shelves hold a mixture of books and objects: a lamp, a plant, some folders, a mug. The whole thing lists slightly. It was made with care and not enough expertise."},
  {n:"Угол у детских игрушек",po:["Сидит среди игрушек","Берёт игрушку","Рассматривает мягкую игрушку","Смотрит в камеру, игрушки вокруг","Складывает игрушки"],bg:"A corner of a room where children's toys have accumulated — a wooden train set, some stuffed animals, scattered building blocks. The floor is visible through the objects. The corner belongs to a child but is being visited by an adult."},
  {n:"Угол у хлебницы",po:["Достаёт хлеб из хлебницы","Нарезает хлеб","Смотрит в камеру у хлебницы","Рукой касается хлебницы","Ставит хлеб в хлебницу"],bg:"A kitchen counter corner with an old bread bin — enamel or wood, with a sliding or hinged lid. Beside it perhaps a breadboard with crumbs. The counter below is marked with the evidence of daily use. A completely unpretentious and beautiful domestic object."},
  {n:"Угол у кухонного окна над раковиной",po:["Стоит у кухонной раковины, смотрит в окно","Моет посуду у окна","Облокотилась на раковину","Смотрит в камеру у раковины","Вытирает руки, смотрит в окно"],bg:"The kitchen sink positioned under a window — the view outside is a garden, a courtyard, or another building, but the light coming in is good. The windowsill holds a small plant. The sink itself shows the evidence of cooking."},
  {n:"Угол у связки ключей",po:["Берёт ключи","Вешает ключи","Ищет ключи среди других","Смотрит в камеру, ключи в руке","Звенит ключами"],bg:"The spot near a door where keys are kept — a hook, a small bowl, or just a habit of a particular surface. Multiple sets of keys, perhaps a few random items that have accumulated there: a coin, a receipt, a small stone from a walk."},
  {n:"Угол у ящика с инструментами",po:["Открывает ящик с инструментами","Достаёт инструмент","Рассматривает инструменты","Облокотилась на ящик","Смотрит в камеру у ящика"],bg:"A toolbox in a corner — a metal cantilever box or a wooden crate, the lid open. Screwdrivers, pliers, a hammer, a tape measure visible inside. The tools are used and real. The surrounding surface has accumulated sawdust or paint flecks."},
  {n:"Угол у детской кроватки",po:["Стоит у кроватки","Облокотилась на перила кроватки","Смотрит в кроватку","Кладёт что-то в кроватку","Смотрит в камеру у кроватки"],bg:"A baby cot in the corner of a bedroom — the sides up, a mobile hanging above, the mattress with a fitted sheet in a soft colour. The room around it has been adapted for the arrival. The light is deliberately soft."},
  {n:"Угол у пакетов с покупками",po:["Разбирает покупки","Достаёт продукт из пакета","Сидит у пакетов с покупками","Смотрит в камеру, пакеты рядом","Ставит пакеты на место"],bg:"The kitchen floor or counter immediately after shopping — bags of groceries not yet unpacked, vegetables visible, a carton of milk, bread. This is the moment between outside and inside, between purchase and use."},
  {n:"Угол у открытого ноутбука",po:["Работает за ноутбуком","Смотрит в экран ноутбука","Закрывает ноутбук","Смотрит в камеру, ноутбук открыт рядом","Пьёт кофе у ноутбука"],bg:"A desk or table corner with an open laptop — the screen glow the main light source, the surroundings dark. Papers, a mug, a charger cable nearby. This is where someone works, studies, or is perpetually online. The most contemporary of domestic corners."},
  {n:"Угол у холста на мольберте",po:["Рисует на холсте","Отступает и смотрит на холст","Держит кисть у холста","Смешивает краски","Смотрит в камеру у мольберта"],bg:"An easel with a canvas in a corner — the painting in progress, some areas resolved and others not. Brushes in a jar nearby, tubes of paint on a surface, the floor below the easel spattered. A corner belonging entirely to making something."},
  {n:"Угол у стеклоблоков",po:["Стоит у стеклоблоков","Рукой касается стеклоблоков","Смотрит сквозь блоки","Свет сквозь блоки на лице","Смотрит в камеру у блоков"],bg:"A wall or partition built from glass blocks — each block slightly rippled, diffusing the light from behind into soft glow. The blocks are thick and heavy-looking. The light they transmit is beautiful and even."},
  {n:"Угол у камня-порога",po:["Стоит на пороге","Одной ногой на пороге, другой нет","Смотрит через порог","Сидит на пороге","Смотрит в камеру, стоя на пороге"],bg:"A doorway with a worn stone threshold — the stone dipped in the centre from decades of footfall, the surface smooth and grey. The difference in floor material on each side clearly visible. A threshold is always a beginning or an end."},
  {n:"Угол у доски для записей",po:["Пишет на доске","Читает записи на доске","Протирает доску","Смотрит в камеру у доски","Указывает на что-то на доске"],bg:"A chalkboard or corkboard on a wall — covered in notes, lists, pinned papers, reminders, a few drawings. The board is full but legible, the life of a household or a working person visible in its contents."},
  {n:"Угол у старой кофеварки",po:["Готовит кофе в кофеварке","Ждёт, пока сварится кофе","Держит кружку у кофеварки","Наливает кофе","Смотрит в камеру у кофеварки"],bg:"An old stovetop moka pot on a gas ring — the coffee just beginning to bubble up. The pot is small and aluminum, stained with use. This is morning, and the smell of coffee is the whole room."},
  {n:"Угол у балконной двери зимой",po:["Смотрит через балконную дверь на снег","Прижалась к холодному стеклу","Открывает балконную дверь зимой","Смотрит в камеру, зима снаружи","Дышит на холодное стекло"],bg:"A balcony door in winter — the glass cold to the touch, the outside world pale and frozen. The room inside is warm and the contrast between inside and outside is total. The outside is quiet and white."},
  {n:"Угол у открытой духовки",po:["Смотрит в духовку","Достаёт что-то из духовки","Ждёт у духовки","Открывает духовку","Смотрит в камеру у плиты"],bg:"The corner of the kitchen at the moment of opening the oven — the door down, the interior warm orange, the smell of whatever is inside filling the space. The face of the person looking in is lit by the oven light."},
  {n:"Угол у шкафчика с зеркалом",po:["Открывает шкафчик","Ищет что-то в шкафчике","Смотрит в камеру у шкафчика","Достаёт таблетки","Закрывает шкафчик"],bg:"A bathroom medicine cabinet with its mirror door open — the shelves inside showing the small medicine collection of a household. The mirror reflects a partial view of the bathroom. The cabinet is chrome or white, the shelves glass or plastic."},
  {n:"Угол у бельевой корзины",po:["Кладёт бельё в корзину","Достаёт бельё из корзины","Сидит у корзины с бельём","Смотрит в камеру у корзины","Сортирует бельё"],bg:"A laundry basket in a corner — wicker or plastic, full or half-full, the contents a private glimpse of daily life. The corner around it might have a few items that did not make it in: a single sock, a shirt."},
  {n:"Угол у ночника у кровати",po:["Включает ночник","Читает у ночника","Смотрит в камеру в свете ночника","Тянется к ночнику","Выключает ночник"],bg:"A small bedside lamp on a low table or clipped to the headboard — the kind that gives just enough light to read by. The shade is fabric or glass, the glow warm and close. The rest of the room is dark. The lamp makes a private world of the bed."}
];

const дорогаLocations = [
  {n:"В купе поезда у столика",po:["Сидит у столика в купе","Смотрит в окно купе","Облокотилась на столик","Держит стакан чая в подстаканнике","Смотрит в камеру в купе"],bg:"The small table area of a train compartment — the folding table down, a glass of tea in a metal holder, the window beside it. The seat is worn plush, the curtain half-drawn. The landscape outside moves. This is the classic long-distance train micro-world."},
  {n:"У окна автобуса ночью",po:["Смотрит в тёмное окно автобуса","Прижалась лбом к холодному стеклу","Отражение в ночном окне автобуса","Засыпает у окна автобуса","Смотрит в камеру, ночь за окном"],bg:"A window seat on a night bus — the outside dark, the window reflecting the interior light back. The seat fabric is slightly scratchy. The world outside is just movement and darkness, punctuated occasionally by passing lights."},
  {n:"Придорожная будка с телефоном",po:["Стоит у телефонной будки","Держит трубку телефона","Смотрит в камеру из будки","Прислонилась к стеклу будки","Набирает номер"],bg:"An old roadside phone box — glass or metal, the kind that still occasionally exists. The directory dog-eared and damp, the receiver heavy and black. Outside the traffic passes or the village is quiet. A relic of a particular kind of travel anxiety."},
  {n:"Угол паромной каюты",po:["Сидит в паромной каюте","Смотрит в иллюминатор парома","Облокотилась на стенку каюты","Лежит на узкой полке","Смотрит в камеру в каюте"],bg:"The narrow interior of a ferry cabin — a bunk, a small porthole showing the sea level, the walls cream-coloured and slightly curved. The motion of the sea is present in everything. The sounds of the engine below and the water outside are constant."},
  {n:"Угол в зале ожидания вокзала",po:["Сидит в зале ожидания","Смотрит на табло","Ждёт с вещами","Смотрит в камеру в зале ожидания","Читает в ожидании"],bg:"A corner of a railway station waiting room — wooden or metal bench, a few other travellers visible. The ceiling is high. The light is institutional but the details are old: a tiled floor, wooden fittings, a clock."},
  {n:"У окна самолёта над облаками",po:["Смотрит в иллюминатор","Прижалась к иллюминатору","Облака за иллюминатором","Смотрит в камеру, иллюминатор рядом","Спит у иллюминатора"],bg:"The window seat of a plane at cruising altitude — the oval window framing a view of cloud tops, impossibly white and three-dimensional below a dark blue sky. The wing of the plane is just visible at the window edge."},
  {n:"Угол придорожного магазина",po:["Смотрит на товары в магазине","Держит что-то с полки","Стоит у витрины","Платит у кассы","Смотрит в камеру в магазине"],bg:"The interior of a small roadside shop — shelves of road food, drinks in a cooler, the kind of shop that exists to serve travellers. The fluorescent light is bright, the floor worn. The products are comforting in their familiarity."},
  {n:"У остановки автобуса на рассвете",po:["Стоит на рассвете у остановки","Смотрит вдоль дороги","Сидит на скамейке остановки","Смотрит в камеру, рассвет за спиной","Держит вещи у остановки"],bg:"A bus stop at dawn — the road empty, the sky just beginning to lighten. The stop itself is simple: a shelter or just a pole, a timetable. The light is that particular early colour that is pink-grey. Nobody else is there."},
  {n:"Угол на палубе корабля",po:["Выходит на палубу","Смотрит на море с борта","Держит поручень","Ветер в волосах на палубе","Смотрит в камеру на палубе"],bg:"The deck of a ship — the rail at the edge, the sea stretching beyond. The rail is painted white, the paint slightly bubbled from salt air. The horizon is a clean line. The wind is constant."},
  {n:"Угол зала выдачи багажа",po:["Ждёт у ленты выдачи багажа","Смотрит на ленту","Берёт чемодан с ленты","Стоит с чемоданом","Смотрит в камеру у ленты"],bg:"The baggage claim area of an airport — the conveyor belt moving slowly, a few bags already going around. The lighting is bright and even. The floor is industrial. This is the moment of waiting that is both arrival and not yet."},
  {n:"В такси ночью",po:["Смотрит в окно такси ночью","Отражение в окне такси","Разговаривает с водителем такси","Смотрит в камеру в такси","Облокотилась на дверь такси"],bg:"The back seat of a taxi at night — the city lights streaming past the window, the driver silhouette in front. The leather or fabric seat, the hanging air freshener, the meter ticking. A private capsule moving through a public city."},
  {n:"Угол у камеры хранения",po:["Открывает ячейку хранения","Складывает вещи в ячейку","Достаёт вещи из ячейки","Стоит у камеры хранения","Смотрит в камеру у ячеек"],bg:"A row of left-luggage lockers in a station or travel hub — metal doors, numbered, some with keys in the locks. The space smells of old metal and transit. The whole system is practical and anonymous."},
  {n:"У стойки регистрации",po:["Стоит у стойки регистрации","Смотрит на монитор регистрации","Передаёт документы","Ждёт у стойки","Смотрит в камеру у стойки"],bg:"A check-in counter at an airport or station — the desk between traveller and operator, the screen at the agent's side showing flight information. The lighting is overhead and flat. The ritual of transition."},
  {n:"Угол у дорожной карты",po:["Изучает дорожную карту","Держит карту","Указывает на что-то на карте","Раскладывает карту на капоте","Сворачивает карту"],bg:"A road map spread open on a surface — paper, large, slightly worn at the folds. The map shows a region in dense typographic detail. The conversation it represents — where are we, how far, which way — is entirely spatial."},
  {n:"На велодорожке за городом",po:["Едет на велосипеде","Стоит с велосипедом","Смотрит вдаль с велосипедом","Облокотилась на велосипед","Смотрит в камеру, велосипед рядом"],bg:"A quiet cycle path between villages — the path tarmac or compacted gravel, edged with grass. The landscape on either side is agricultural. No cars here, just the path stretching in both directions."},
  {n:"Угол у вагона-ресторана",po:["Сидит в вагоне-ресторане","Смотрит в окно вагона-ресторана","Ест в вагоне-ресторане","Держит бокал в вагоне-ресторане","Смотрит в камеру в вагоне-ресторане"],bg:"The dining car of a long-distance train — tables set with white cloth and small vase, the landscape moving past the window outside. The food is modest but the setting has a specific pleasure. The car sways gently with the track."},
  {n:"У терминала автобусной станции",po:["Стоит у автобусной платформы","Ждёт автобуса с вещами","Смотрит на расписание","Садится в автобус","Смотрит в камеру на станции"],bg:"A regional bus terminal — the platforms under a simple canopy roof, the buses lined up or arriving. The surface is concrete, the markings worn. This is how most people in most places travel."},
  {n:"Угол у лодки у берега",po:["Сидит в лодке","Толкает лодку от берега","Стоит у лодки","Облокотилась на борт лодки","Смотрит в камеру у лодки"],bg:"A small rowing boat or motorboat moored at a simple wooden dock — the boat painted, the paint peeling in places, the water visible between boat and dock. The water moves the boat gently. A lake or river beyond."},
  {n:"Угол в кемпинге у фонаря",po:["Сидит у кемпингового фонаря","Держит фонарь","Освещена фонарём ночью","Читает у кемпингового фонаря","Смотрит в камеру, фонарь рядом"],bg:"A camping spot at night — a lantern providing the only light, the warm glow falling on the immediate area: a camp chair, a table, a person. Beyond the light is dark woods or dark field. The lantern is the entire world made small and warm."},
  {n:"Угол у придорожной часовни",po:["Стоит у часовни","Заглядывает внутрь часовни","Рукой касается стены часовни","Смотрит в камеру у часовни","Кладёт цветок у часовни"],bg:"A small roadside chapel or shrine — whitewashed, about the size of a doorway. Inside a few candles, an icon or small statue, wilted flowers from previous visitors. The road passes very close. The contrast between traffic and this tiny still space is complete."},
  {n:"Угол у тропинки в лесу",po:["Стоит на лесной тропинке","Идёт по тропинке","Сидит у тропинки на корне","Смотрит вдоль тропинки","Смотрит в камеру на тропинке"],bg:"A forest path — narrow, pine needles or leaf mould underfoot, the trees close on either side making a green tunnel. The light filters through and dapples the path. The path curves ahead and becomes uncertain."},
  {n:"Угол у заправки ночью",po:["Стоит у колонки заправки","Смотрит на заправку ночью","Идёт к магазину заправки","Освещена светом заправки","Смотрит в камеру у заправки"],bg:"A petrol station at night — the canopy brilliantly lit against the dark, the pumps standing in their pool of fluorescent light. The road beyond is completely dark. The station is an island of harsh light in the rural night."},
  {n:"В лифте с чемоданом",po:["Едет в лифте с чемоданом","Стоит в лифте с вещами","Смотрит в зеркало лифта","Смотрит вверх в лифте","Смотрит в камеру в лифте"],bg:"The interior of a hotel or apartment building lift — small, mirrored, a suitcase taking up half the space. The mirror gives an infinite regression of reflected luggage. The lift is the transitional space between arrival and being there."},
  {n:"У окна поезда на рассвете",po:["Смотрит в рассветное окно поезда","Просыпается у окна поезда","Прижалась к стеклу","Освещена рассветным светом в поезде","Смотрит в камеру, рассвет за окном"],bg:"A train window at first light — the world outside transitioning from dark to pale, the fields and farms beginning to be visible. Inside the carriage is still dim and quiet, other passengers asleep. The light is the colour of water before colour arrives."},
  {n:"У придорожной кормушки для птиц",po:["Смотрит на птиц у кормушки","Кладёт корм в кормушку","Стоит у кормушки","Рукой касается кормушки","Смотрит в камеру у кормушки"],bg:"A roadside bird table or feeder — a simple wooden structure at the edge of a lay-by or rest area. Sparrows and finches visiting in small rapid movements. The traveller who stops here has stopped specifically for this, for the birds, for the pause."},
  {n:"Угол у паромного причала",po:["Ждёт парома на причале","Смотрит на воду у причала","Стоит у парома","Смотрит вдаль с причала","Смотрит в камеру на причале"],bg:"A ferry terminal dock — the ramp down into the water, the bollards thick and rusted, the rope lines looped and waiting. The water below is dark and the smell of diesel and salt. The far shore visible or not depending on the weather."},
  {n:"Угол у горного кафе",po:["Сидит в горном кафе","Держит кружку у горного кафе","Смотрит в окно горного кафе на горы","Согревается в горном кафе","Смотрит в камеру в кафе"],bg:"The inside of a small mountain cafe — the windows fogged with condensation, the outside showing grey rock and perhaps snow. The interior is warm and basic: wooden tables, a counter with a coffee machine. Skis or hiking poles lean against the wall outside."},
  {n:"На трассе в тумане",po:["Стоит в тумане у дороги","Смотрит вдаль в туман","Идёт в тумане","Освещена фарами в тумане","Смотрит в камеру, туман за спиной"],bg:"A roadside stopped in fog — the tarmac visible for a few metres before it dissolves into white nothing. The edges of the road disappear. Other vehicles are just shapes and then sounds. The fog is total and the isolation inside it is complete."},
  {n:"Угол у мотельного номера",po:["Стоит в мотельном номере","Кладёт вещи в мотельном номере","Смотрит на кровать мотельного номера","Смотрит в камеру в мотеле","Открывает шторы в мотеле"],bg:"A motel room — the bed with its tightly fitted cover, the bedside lamp on a low table, a wardrobe against one wall. The curtains are heavy and block the light. The room is generic but there is something about its anonymity that is restful."},
  {n:"Угол у пограничного поста",po:["Стоит у пограничного поста","Ждёт у шлагбаума","Смотрит в камеру у границы","Протягивает документы","Держит паспорт у границы"],bg:"The waiting area near a border crossing — a booth with an official barely visible inside, a striped barrier, the space between countries that is technically neither. Waiting here is the whole experience."},
  {n:"У окна поезда в поле",po:["Смотрит в окно поезда на поле","Облокотилась на стекло","Смотрит в камеру, поле за окном","Открывает окно поезда","Смотрит вдаль в поле"],bg:"A train window level with a passing field — the view flat and agricultural, the crops or stubble moving past in a continuous blur of yellow and green. The sky above the field is large and the horizon very distant."},
  {n:"Угол у горного ручья",po:["Стоит у горного ручья","Пьёт воду из ручья","Сидит у ручья","Опускает руку в воду","Смотрит в камеру у ручья"],bg:"A mountain stream beside a walking path — the water clear and fast over smooth stones, the sound constant and cold. The stones in the bed are various sizes and colours. The stream passes through without stopping."},
  {n:"Угол у дорожного указателя",po:["Стоит у дорожного указателя","Смотрит на указатель","Указывает на знак","Смотрит в камеру у указателя","Делает выбор у развилки"],bg:"A road junction with a signpost — the kind with several arms pointing in different directions, each naming a place and giving a distance in kilometres. The choice of direction is the whole story. Sky above, road in multiple directions."},
  {n:"В аэропортовом транзите",po:["Идёт по аэропортовому коридору","Сидит в транзитной зоне","Смотрит в транзитное окно","Спит в транзитной зоне","Смотрит в камеру в транзите"],bg:"The transit zone of an international airport — the long corridor between gates, the floor shining, the duty-free shops lit in a way that makes time unreadable. The city outside is invisible. The clocks show multiple time zones."},
  {n:"На причале у рыбацких лодок",po:["Сидит на причале у лодок","Смотрит на рыбацкие лодки","Держится за канат лодки","Стоит на причале","Смотрит в камеру у рыбацкого причала"],bg:"A small fishing harbour — the boats low in the water, painted in working colours, the nets and equipment visible in the hulls. The dock is wooden or stone, the bollards rusted. The smell of fish and diesel and salt is total."},
  {n:"Угол у информационного центра",po:["Изучает карту в туристическом центре","Разговаривает с сотрудником центра","Стоит у брошюр","Держит туристическую брошюру","Смотрит в камеру в туристическом центре"],bg:"The interior of a small tourist information office — the stands of leaflets and maps, the smiling faces on the brochures, the person at the desk surrounded by local knowledge. The maps and brochures are free and slightly out of date."},
  {n:"Угол у горного перевала",po:["Стоит на перевале","Смотрит вниз с перевала","Ветер на перевале","Смотрит в камеру на перевале","Делает шаг вперёд на перевале"],bg:"The top of a mountain pass — the road narrowing here, the views on both sides opening to valleys. The wind is reliable and cold. A small monument might be at the exact highest point. The descent on both sides reveals two different landscapes."},
  {n:"В поезде у откидного столика",po:["Ест у откидного столика в поезде","Раскладывает вещи на столике","Держит стакан у откидного столика","Работает за столиком в поезде","Смотрит в камеру, столик перед ней"],bg:"A folding tray table on a train or plane seat — the surface just large enough for a laptop or a meal. On it right now: a container of food, a napkin, a plastic cutlery set. The window beside it shows the world moving past."},
  {n:"Угол у кемпинговой палатки",po:["Выходит из палатки","Стоит у входа в палатку","Смотрит в небо у палатки","Готовит у палатки","Смотрит в камеру у палатки"],bg:"The entrance of a camping tent — the flysheet back, the interior visible with a sleeping bag and small lamp. The ground outside is grass or rock, the surroundings either forest or field. The morning light shows the dew on the tent fabric."},
  {n:"Угол у старой автозаправки",po:["Стоит у старой колонки","Рукой касается ретро-колонки","Смотрит на старую заправку","Облокотилась на колонку","Смотрит в камеру у колонки"],bg:"An old petrol station that has stopped serving fuel but not been demolished — the pumps still standing, the paint faded to a specific era colour, the canopy slightly bent. The forecourt is cracked and weeds are coming through. A roadside ruin."},
  {n:"Угол у двери поезда у платформы",po:["Стоит у двери поезда","Садится в поезд","Машет с перрона","Смотрит из вагона на перрон","Смотрит в камеру у поезда"],bg:"The moment of a train at a platform — the train door open, the step down to the platform visible, the interior of the carriage behind. The platform is concrete, the train's side close. This is the last moment before the journey begins."},
  {n:"Угол у паромного буфета",po:["Стоит в очереди буфета парома","Берёт поднос в буфете","Ест у окна на пароме","Держит кофе на пароме","Смотрит в камеру в буфете парома"],bg:"The cafeteria of a car ferry — plastic trays, the self-service counter with hot food, the large windows showing the open sea. The seating is bolted to the floor against the movement of the ship. The food is basic and hot and exactly what a long ferry crossing requires."},
  {n:"У светофора на пустой дороге",po:["Стоит у светофора","Смотрит на красный свет","Смотрит в камеру у светофора","Пересекает дорогу по переходу","Ждёт зелёного сигнала"],bg:"A traffic light at a rural crossroads — the only light for several kilometres in any direction, the signal going through its cycle for no particular reason at this hour. The road is empty. The light turns green. Nothing moves."},
  {n:"Угол у речной переправы",po:["Ждёт переправы у реки","Смотрит на переправу","Едет на пароме-переправе","Стоит у берега реки","Смотрит в камеру у переправы"],bg:"A river crossing point — a small cable ferry that crosses under its own power. The river is wide and slow here. The opposite bank is close but separated. The water between is the whole journey."},
  {n:"Угол у вокзального буфета",po:["Стоит у буфета на вокзале","Берёт кофе в буфете","Ест у стойки буфета","Смотрит на витрину буфета","Смотрит в камеру у буфета"],bg:"A station buffet counter — the glass case showing sandwiches and pastries under bright light, the coffee machine hissing. The counter is high and there are no seats, just the standing bar. The trains are visible through the window. Everything here is quick."},
  {n:"У шлагбаума на переезде",po:["Ждёт у железнодорожного переезда","Смотрит на приближающийся поезд","Стоит у шлагбаума","Смотрит в камеру у переезда","Смотрит вдоль рельсов"],bg:"A level crossing — the barrier down, the lights flashing red, the warning bell ringing. The train has not yet appeared but can be heard. The road on both sides is empty. This is one of the most specific moments of enforced waiting that travel produces."},
  {n:"В автомобиле на парковке",po:["Сидит за рулём на парковке","Смотрит в зеркало заднего вида","Облокотилась на руль","Смотрит в камеру из машины","Достаёт что-то из бардачка"],bg:"The interior of a car stopped in a car park — the engine off, the windows showing other cars and a flat sky. The dashboard, the steering wheel, the handbrake. This is the pause between arrival and wherever inside you are going."},
  {n:"Угол у автобусного депо",po:["Стоит у автобусного депо","Смотрит на автобусы в депо","Прислонилась к забору депо","Смотрит в камеру у депо","Идёт вдоль ряда автобусов"],bg:"The edge of a bus depot — the buses lined up in rows, all facing the same direction, the depot walls painted the regulation colour. The scale is different from a street: everything is larger. The buses at rest look patient and enormous."},
  {n:"Угол у вагонного тамбура",po:["Стоит в тамбуре поезда","Смотрит в окно тамбура","Прислонилась к стенке тамбура","Смотрит в камеру в тамбуре","Открывает дверь тамбура"],bg:"The vestibule of a train car — the space between carriages, slightly noisier than inside, the joints of the train visible in the floor, the door window showing the tracks going by. Passengers pass through quickly. Standing here feels transitional and slightly daring."},
  {n:"У стоянки такси",po:["Стоит в очереди такси","Садится в такси","Смотрит на ряд такси","Разговаривает с водителем такси","Смотрит в камеру у стоянки"],bg:"A taxi rank outside a station or airport — the cars in a line, the drivers waiting, the luggage going in and out. The canopy overhead, the pavement marked with a queue guide. The moment of getting in marks the end of the public journey and the beginning of a private one."}
];

const городLocations = [
  {n:"Угол у стеклянной витрины",po:["Смотрит в витрину","Заглядывает в окно магазина","Прислонилась к витрине","Отражение в витрине","Смотрит в камеру у витрины"],bg:"A large shop window reflecting the street — the merchandise behind the glass slightly secondary to the reflections on its surface: the opposite buildings, a passing bus, the sky. The subject is between the reflection and the real, visible in both."},
  {n:"Угол у водосточной трубы",po:["Прислонилась к водосточной трубе","Стоит рядом с трубой","Рукой обхватила трубу","Смотрит вверх по трубе","Смотрит в камеру у трубы"],bg:"An old cast iron drainpipe running down the corner of a building — painted and repainted many times, the colour now a dark green or black. The brackets fixing it to the wall are at regular intervals. The pipe is solid and very vertical."},
  {n:"Угол у лавочки с голубями",po:["Сидит на лавочке у голубей","Кормит голубей","Смотрит на голубей на лавочке","Прогоняет голубя","Смотрит в камеру, голуби рядом"],bg:"A public bench where pigeons have completely taken over — four or five birds on the seat and back, the bench itself streaked white from their long occupation. The birds are entirely unbothered by the intrusion."},
  {n:"Угол у афишной тумбы",po:["Читает афишу на тумбе","Прислонилась к афишной тумбе","Смотрит на объявления","Обходит вокруг тумбы","Смотрит в камеру у тумбы"],bg:"A cylindrical advertising pillar — the classic rounded column covered in layered posters and bills, some torn, some complete, the layers creating a history of recent weeks in the city. The structure is old and slightly tilted."},
  {n:"Угол у рынка со свежей зеленью",po:["Выбирает зелень на рынке","Держит пучок зелени","Нюхает зелень","Разговаривает с продавцом зелени","Смотрит в камеру у зелени"],bg:"A market stall selling fresh herbs and salad greens — bunches of parsley, dill, basil, mint arranged in the cool. The colours are very green and vivid. The seller's hands have been in cold water all morning. The smell is fresh and sharp."},
  {n:"Угол у старой табличной вывески",po:["Смотрит на вывеску","Указывает на вывеску","Прислонилась к стене под вывеской","Фотографирует вывеску","Смотрит в камеру под вывеской"],bg:"An old hand-painted shop sign on the building wall — the lettering traditional, slightly faded, the trade it announces perhaps still operating or long gone. The paint on the sign and the paint on the building wall are the same age and tone."},
  {n:"Угол у уличного пианино",po:["Играет на уличном пианино","Стоит у уличного пианино","Слушает игру у пианино","Кладёт руки на клавиши","Смотрит в камеру у уличного пианино"],bg:"A public street piano — the upright standing on a pavement or in a pedestrian area, somewhat weathered, the keys open and available. The paint on the case might be bright, repainted by volunteers. Someone has left a piece of sheet music on the stand."},
  {n:"Угол у уличного фонтанчика",po:["Пьёт из уличного фонтанчика","Стоит у фонтанчика","Льёт воду на руки","Смотрит в камеру у фонтанчика","Набирает воду в бутылку"],bg:"A street drinking fountain — old, iron or stone, the water running constantly or on a button press. The basin below is stained green with algae around the drain. The mouth of the tap is worn smooth. Free water in the city, ancient and reliable."},
  {n:"Угол у городской стены с плющом",po:["Прислонилась к стене с плющом","Рукой касается плюща","Стоит у стены в тени плюща","Смотрит в камеру, плющ вокруг","Смотрит вверх на плющ"],bg:"An old stone or brick wall almost entirely covered in ivy — the leaves dense and layered, the wall beneath barely visible. In summer the ivy is deep green, in autumn turning red and orange. The ivy has been growing for decades."},
  {n:"Угол у городской фотобудки",po:["Входит в фотобудку","Выходит из фотобудки с фотографиями","Ждёт фотографий у будки","Смотрит в камеру у фотобудки","Держит ленту фотографий"],bg:"A photo booth on a street or in a station — the small curtained box, the stool inside at the right height. On the ground outside, the rejected test strips of other people's sessions are sometimes visible. The wait for the photos to emerge is exactly forty-five seconds."},
  {n:"Угол у городского сквера",po:["Сидит в сквере","Смотрит на сквер","Проходит через сквер","Стоит у края сквера","Смотрит в камеру в сквере"],bg:"A small urban square — a few benches, perhaps a fountain or a tree, the buildings close on all sides. The square is the size of a courtyard, just open enough to breathe. The usual quiet occupation of a neighbourhood square at a particular hour."},
  {n:"Угол у уличного художника",po:["Смотрит на работу уличного художника","Разговаривает с уличным художником","Рассматривает работы в витрине","Держит работу художника","Смотрит в камеру у художника"],bg:"A pavement artist's pitch — the work spread on the ground or displayed on a folding stand, watercolours or prints of the city. The artist works or watches. The surface under the work is cobblestone or pavement."},
  {n:"Угол у городской будки охраны",po:["Проходит мимо будки","Стоит у будки","Смотрит в будку","Смотрит в камеру у будки","Прислонилась к стенке будки"],bg:"A security booth at the entrance to a building or car park — small, glass-walled, a chair visible inside. The booth is painted institutional grey or cream. The barrier beside it is up or down."},
  {n:"Угол у городского фонтана",po:["Стоит у фонтана","Трогает воду фонтана","Сидит на бортике фонтана","Смотрит на воду в фонтане","Смотрит в камеру у фонтана"],bg:"A neighbourhood fountain — not grand, functional scale, perhaps in the centre of a small square. The water falls from a simple spout, the basin below showing coins through the water. The sound of the water is audible even with traffic nearby."},
  {n:"Угол у магазина газет",po:["Выбирает газету","Читает заголовок","Стоит у стенда с газетами","Покупает газету","Смотрит в камеру у газетного стенда"],bg:"A newspaper kiosk or corner newsstand — the magazines and papers fanned out in their racks, the headlines visible, the colours dense. The vendor behind the counter has been there since early morning. The stand is always full and always slightly chaotic."},
  {n:"Угол у пожарной лестницы",po:["Стоит у лестницы пожарного выхода","Взбирается по лестнице","Смотрит вверх по лестнице","Держится за перила лестницы","Смотрит в камеру у лестницы"],bg:"An exterior fire escape on the side of a building — the zigzag metal stairs and landings attached to the brick facade. The metal is painted black or rust-red, the paint chipped. The stairs serve as a vertical path up the outside of the building."},
  {n:"Угол у городского колодца",po:["Стоит у городского колодца","Рукой касается кольца колодца","Смотрит вниз в колодец","Опускается к колодцу","Смотрит в камеру у колодца"],bg:"An old city well — no longer functional, preserved as a monument in a small square or courtyard. The stone rim is smooth from generations of hands. The cover or chain still there. The well is circular and deep and silent."},
  {n:"Угол у граффити-надписи",po:["Читает граффити на стене","Прислонилась к стене с граффити","Стоит перед надписью","Смотрит в камеру, граффити за спиной","Рукой касается букв граффити"],bg:"A wall with a single spray-painted word or phrase — not a mural but text only, in a bold hand. The letters are large and the colour stands out from the wall surface. The act of writing on a public wall is simple and defiant."},
  {n:"Угол у городской доски объявлений",po:["Читает объявления","Прикрепляет объявление","Снимает объявление","Стоит у доски","Смотрит в камеру у доски объявлений"],bg:"A community notice board in a neighbourhood — covered in local announcements, lost cat posters, language exchange offers, political leaflets. Everything is slightly damp and overlapping. The board is the hyper-local conversation of a neighbourhood."},
  {n:"Угол у городского пруда",po:["Сидит у пруда","Бросает хлеб уткам","Смотрит на воду пруда","Прогуливается у пруда","Смотрит в камеру у пруда"],bg:"A small ornamental pond in a city park — the water dark green, a few ducks. The edge is concrete or stone, worn smooth. The park around the pond is modest: a few benches, some old trees. The pond is the still centre of the surrounding city noise."},
  {n:"Угол у выпуклого зеркала в переулке",po:["Смотрит в уличное зеркало","Проверяет себя в уличном зеркале","Прислонилась рядом с зеркалом","Смотрит в камеру у зеркала","Поправляет волосы у зеркала"],bg:"A convex traffic mirror at a blind corner of a narrow street — the round mirror showing a wide-angle view of the lane behind. The reflection in it is distorted and all-encompassing. The mirror is bolted to the wall at head height."},
  {n:"Угол у деревянных ставней на лавке",po:["Стоит у закрытой лавки","Рукой трогает деревянные ставни","Заглядывает в щель ставен","Смотрит в камеру у ставен","Прислонилась к ставням"],bg:"A small shop with its wooden shutters down — the shop closed, the shutters old and painted a faded colour, perhaps with the shop name stencilled above. The pavement in front is clean. The shop could open tomorrow or have closed for good years ago."},
  {n:"Угол у городских часов",po:["Смотрит на городские часы","Стоит под часами","Ждёт под часами","Проходит мимо часов","Смотрит в камеру, часы видны"],bg:"A public clock on the outside of a building or on a post — the face large and readable, the hands showing the actual time. The clock is old enough to have a history but young enough to still be accurate. People arrange to meet beneath it."},
  {n:"Угол у улочки с арками",po:["Идёт под аркой","Стоит в арке","Смотрит вдоль арочного прохода","Прислонилась к арке","Смотрит в камеру в арке"],bg:"A narrow street passing under a sequence of arches — the buildings on both sides so old they have been connected above by arched bridges or the arch is cut through the building itself. The light is interrupted and then restored. The passage makes a tunnel of the street."},
  {n:"Угол у городского рынка с сырами",po:["Выбирает сыр на рынке","Держит кусок сыра","Нюхает сыр","Разговаривает с продавцом сыра","Смотрит в камеру у сырного прилавка"],bg:"A cheese stall at a market — the rounds and wedges arranged on a draped table, some cut open to show the interior. The smell is complex and strong. The seller cuts samples with a long-handled knife. The selection is local and serious."},
  {n:"Угол у городских ступеней",po:["Идёт вверх по ступеням","Сидит на ступенях","Смотрит вниз со ступеней","Стоит на ступенях","Смотрит в камеру на ступенях"],bg:"A flight of old stone steps rising between buildings on a hill — the steps worn uneven, each a slightly different height. The walls on both sides are close. The view at the top is the reward. The steps smell of old stone and time."},
  {n:"Угол у почтового ящика в стене",po:["Опускает письмо в ящик","Стоит у почтового ящика","Рукой касается почтового ящика","Смотрит в камеру у почтового ящика","Ждёт у почтового ящика"],bg:"A post box set into a wall or standing on a post — the cast iron painted red or yellow depending on the country, the slot for letters in the front. The collection time is printed on a small plate. The box is full or empty, the weight of correspondence invisible inside."},
  {n:"Угол у уличного самовара",po:["Наливает чай из самовара","Держит стакан чая","Стоит у самовара","Ждёт стакана у самовара","Смотрит в камеру у самовара"],bg:"A street samovar or tea urn — an outdoor spot where tea is served, the samovar brass and steaming, the cups stacked beside it. The vendor has set up under an awning. The tea is strong and sweet and it is cold enough to need it."},
  {n:"Угол у городской брусчатки",po:["Стоит на брусчатке","Сидит на краю мостовой","Смотрит на брусчатку","Идёт по брусчатке","Смотрит в камеру, брусчатка под ногами"],bg:"A stretch of old cobblestone street — the stones rounded and fitted by hand, the surface uneven. Between the stones the moss grows in the gaps. The sound of heels on cobblestone is particular to this surface."},
  {n:"Угол у балконов с бельём",po:["Стоит под бельём на балконах","Смотрит вверх на бельё","Смотрит в камеру, бельё над головой","Идёт под балконами с бельём","Прислонилась к стене под бельём"],bg:"A narrow street between buildings where laundry is strung between balconies above — the sheets and clothing overlapping at different heights, the light filtered through the hanging fabric. The laundry belongs to many different households."},
  {n:"Угол у антикварной лавки",po:["Рассматривает витрину антиквариата","Заглядывает в антикварную лавку","Стоит у витрины","Смотрит в камеру у лавки","Рукой касается предмета в витрине"],bg:"The window of an antique shop — objects crowded against the glass: a clock, a painting, ceramics, lamps, a silver dish. The interior beyond is dim and full. The window display has not changed in several months. The shop is open but no one is inside."},
  {n:"Угол у ниши со статуей",po:["Стоит у ниши со статуей","Смотрит на статую в нише","Рукой касается постамента","Смотрит в камеру у статуи","Смотрит снизу вверх на статую"],bg:"An architectural niche set into the facade of a building holding a small stone or terracotta figure — a saint, a classical figure, a civic emblem. The figure inside worn by weather. The building around it continues its ordinary life."},
  {n:"Угол у городского цветочного ряда",po:["Выбирает цветы","Нюхает цветок","Держит букет","Разговаривает с продавцом цветов","Смотрит в камеру среди цветов"],bg:"A pavement flower seller with their stock arranged on a folding table and in buckets on the ground — peonies, roses, tulips, whatever is in season. The seller wraps a bunch in paper while talking. The pavement smells of water and stems."},
  {n:"Угол у уличного кофейного автомата",po:["Берёт кофе из уличной машины","Нажимает на кнопку кофемашины","Стоит у кофемашины","Пьёт кофе у уличной машины","Смотрит в камеру у кофемашины"],bg:"A standalone coffee vending machine on a pavement or in a transit area — the machine slightly battered, the selection of drinks illuminated. The cup drops and the coffee follows. The machine is part of no particular establishment. It serves the street itself."},
  {n:"Угол у проката велосипедов",po:["Берёт велосипед из стойки","Ставит велосипед в стойку","Стоит у велосипедной стойки","Смотрит в камеру у велопроката","Выбирает велосипед"],bg:"A bike-share docking station — a row of identical bicycles in a metal rack, some docked and some missing. The bikes are a single colour, boxy and upright. The docking terminal nearby shows availability. An urban infrastructure moment, quietly democratic."},
  {n:"Угол у старого кинотеатра",po:["Смотрит на афишу кинотеатра","Стоит у входа в кинотеатр","Покупает билет","Ждёт у входа в кинотеатр","Смотрит в камеру у кинотеатра"],bg:"The entrance lobby or marquee of an old cinema — the letters of the current film arranged in the traditional manual reader board. The carpet inside is patterned and slightly worn. The smell is popcorn and old air conditioning."},
  {n:"Угол у трамвайных рельсов",po:["Стоит у трамвайных рельсов","Смотрит вдоль рельсов","Переходит трамвайные пути","Ждёт трамвая у рельсов","Смотрит в камеру у трамвайных путей"],bg:"A section of city street where tram tracks are set into the cobblestone or asphalt — the rails shining and precise, curving slightly away down the street. The tram is coming or has just gone."},
  {n:"Угол у детского аттракциона",po:["Смотрит на детский аттракцион","Стоит у карусели","Наблюдает за детьми","Смотрит в камеру у аттракциона","Покупает билет на аттракцион"],bg:"A small coin-operated children's ride on a pavement — a horse, a car, a plane, brightly painted, slightly faded. The machine waits for a coin. Around it the pavement is marked with the scuffs of generations of small shoes."},
  {n:"Угол у городского тупика",po:["Стоит в тупике","Смотрит вдоль тупика","Прислонилась к стене тупика","Смотрит в камеру в тупике","Разворачивается в тупике"],bg:"A dead-end alley — the lane narrowing and then ending at a wall. The light in the alley is dim. What is here: a drain, some bins, the backs of buildings on three sides. A complete and overlooked corner of the city."},
  {n:"Угол у строительного ограждения",po:["Стоит у строительного ограждения","Смотрит сквозь щель в ограждении","Прислонилась к ограждению","Смотрит в камеру у ограждения","Рукой касается сетки"],bg:"The green mesh screen around a construction site — the building behind invisible, the screen printed perhaps with an artist's impression of what will be there. The pavement narrows beside the hoarding."},
  {n:"Угол у парикмахерской",po:["Смотрит в зеркало парикмахерской","Проходит мимо зеркала","Поправляет волосы у зеркала","Смотрит в камеру у зеркала","Прислонилась к стене у зеркала"],bg:"The window of a barber shop or hairdresser — the interior visible: a chair, a mirror, combs in blue liquid, the barber working or waiting. The exterior sign has the traditional pole or just painted lettering. The window is often steamed."},
  {n:"Угол у городского памятника",po:["Стоит у основания памятника","Смотрит вверх на памятник","Рукой касается постамента","Сидит у подножия памятника","Смотрит в камеру у памятника"],bg:"A modest civic monument on a small pedestal — not a famous landmark but the kind of local monument that only the neighbourhood knows. The inscription is worn. Flowers are sometimes left, sometimes not."},
  {n:"Угол у прачечной-самообслуживания",po:["Загружает вещи в машину","Ждёт у стиральной машины","Смотрит в барабан стиральной машины","Складывает бельё","Смотрит в камеру в прачечной"],bg:"The interior of a laundromat — the machines in a row, the plastic chairs waiting, the light fluorescent. One machine is running, the clothes tumbling. The sound of the water and the drum. Someone has left a magazine on the chair."},
  {n:"Угол у велопарковки",po:["Пристёгивает велосипед","Отстёгивает велосипед","Стоит у велосипеда","Ищет велосипедный замок","Смотрит в камеру у велопарковки"],bg:"A crowded bicycle parking area — bikes of all kinds locked to every available point: a stand, a railing, a lamp post. The density of bikes makes its own small forest of handlebars and wheels."},
  {n:"Угол у уличного светильника",po:["Прислонилась к фонарному столбу","Стоит у фонаря","Облокотилась на фонарный столб","Смотрит вверх на фонарь","Смотрит в камеру у фонаря"],bg:"An old street lamp — the post cast iron, the lantern glass and metal, the light gas-style though electric. The pool of light it creates at night is the whole story."},
  {n:"Угол у водонапорной башни",po:["Смотрит на водонапорную башню","Стоит у основания башни","Прислонилась к башне","Смотрит вверх на башню","Смотрит в камеру у башни"],bg:"An old water tower on the edge of a neighbourhood — the brick structure rising above the surrounding houses, the tank on top no longer functional. The brickwork is Victorian or Edwardian, the architectural detail excessive for a utilitarian structure."},
  {n:"Угол у книжного развала",po:["Выбирает книгу на развале","Держит книгу","Листает книгу","Платит за книгу на развале","Смотрит в камеру у книжного развала"],bg:"A second-hand book stall on the pavement — the books in boxes or on folding tables, spines up, the stock a complete accident of donations. The prices are in pencil on the first page. The stall is run by someone who has been here every weekend for twenty years."},
  {n:"Угол у городского рынка специй",po:["Нюхает специи на рынке","Выбирает специю","Держит пакет специй","Разговаривает с продавцом специй","Смотрит в камеру у специй"],bg:"A spice stall in an urban market — the cones and bags of coloured powders: turmeric, chilli, sumac, paprika. The colours are intense and dry-looking. The seller scoops from the cone with a small flat scoop. The air tastes of cumin."},
  {n:"Угол у городской арки прохода",po:["Стоит под аркой прохода","Проходит сквозь арку","Смотрит в арку","Прислонилась к арке","Смотрит в камеру, арка над головой"],bg:"A wide covered passageway cut through a block of buildings — the arch at the entrance, the passage longer than it looks, the other end visible as a bright rectangle. The walls of the passage are old stone or plaster. The passage connects two different streets."},
  {n:"Угол у городского рынка с мёдом",po:["Пробует мёд на рынке","Держит банку мёда","Рассматривает виды мёда","Разговаривает с пасечником","Смотрит в камеру у мёда"],bg:"A honey stall at a farmers market — rows of jars from pale acacia to dark buckwheat, the light shining through them amber and gold. The beekeeper has small samples on wooden sticks. The jars are various sizes with hand-printed labels."}
];

// ─── serialise ───────────────────────────────────────────────────────────────

function loc2js(loc, mkRef, c) {
  const po = loc.po.map(p => JSON.stringify(p)).join(',');
  return `{n:${JSON.stringify(loc.n)},c:${JSON.stringify(c)},mk:${mkRef},ot:otBase,po:[${po}],bg:${JSON.stringify(loc.bg)}}`;
}

const portLines = портретLocations.map(l => loc2js(l, 'mkPort', 'портрет'));
const domLines  = домLocations.map(l => loc2js(l, 'mkDom', 'дом'));
const dorLines  = дорогаLocations.map(l => loc2js(l, 'mkDor', 'дорога'));
const gorLines  = городLocations.map(l => loc2js(l, 'mkGor', 'город'));

const insertion = `
const mkPort = ["Портретный нюд: ровный тон, тонкие стрелки, матовые губы","Студийный: чёткие брови, smoky нюд, хайлайтер","Натуральный свет: BB-крем, только тушь, прозрачный глосс","Мягкая классика: матовая кожа, коричневые тени, бежевая помада","Сияние: хайлайтер, розово-персиковые тени, нюдовый глосс","Графичный: стрелки, нюдовые губы, скульптурный контур"];
const mkDom = ["Утренний нюд: BB-крем, подкрашенные ресницы, прозрачный блеск","Домашний уют: матовый тон, коричневые тени, нюдовые губы","Мягкий дневной: хайлайтер, нежные румяна, глосс","Минимализм: только тушь и консилер, натуральная кожа","Тёплый беж: бронзер, тауп-тени, матовая помада","Нежный акварель: розовые тени, коралловый блеск, лёгкий тон"];
const mkGor = ["Городской нюд: матовый тон, подчёркнутые брови, нюдовые губы","Уличный стиль: BB-крем, смоки нюд, глосс","Casual chic: бронзер, тауп-тени, матовая помада","Свежий день: нежный тон, тушь, прозрачный блеск","Осенний город: охровые тени, матовая нюдовая помада, контур","Дневной минимализм: только тушь и консилер, натуральная кожа"];
const mkDor = ["Дорожный нюд: BB-крем, тушь, бальзам","Ветреный день: матовый тон, коричневые тени, нюдовые губы","Свежий: хайлайтер, нежные румяна, прозрачный блеск","Минимализм в пути: только тушь и консилер","Тёплый: бронзер, тауп-тени, матовая помада","Городской casual: матовый тон, смоки нюд, глосс"];
const otBase = ["Кроп-топ с балконет-вырезом + прямые джинсы + кеды","Блуза с плунже-декольте + широкие брюки + лоферы","Боди с балконет-вырезом + джинсы скинни + мюли","Бралет из плотного трикотажа + оверсайз пальто + прямые джинсы + ботинки","Рубашка с плунже-вырезом завязана на талии + джинсы + кеды","Корсет-топ + широкие брюки + лоферы","Бомбер + боди с балконет-вырезом + джинсы + кеды","Блуза с балконет-вырезом, рукав 3/4 + кюлоты + лоферы","Худи с балконет-вырезом кроп + джинсы + кроссовки","Топ с бралет-лифом + ветровка нараспашку + джинсы + кроссовки"];
LOC.push(...[${portLines.join(',\n')}]);
LOC.push(...[${domLines.join(',\n')}]);
LOC.push(...[${dorLines.join(',\n')}]);
LOC.push(...[${gorLines.join(',\n')}]);
`;

// ─── file patching ────────────────────────────────────────────────────────────

// fs already required
const filePath = '/home/user/photojob/index.html';

let html = fs.readFileSync(filePath, 'utf8');

// Find last LOC.push(
let lastPushIdx = -1;
let pos = 0;
while (true) {
  const idx = html.indexOf('LOC.push(', pos);
  if (idx === -1) break;
  lastPushIdx = idx;
  pos = idx + 1;
}

if (lastPushIdx === -1) { console.error('No LOC.push( found'); process.exit(1); }

// Walk forward counting parens to find matching close )
let depth = 0;
let i = lastPushIdx + 'LOC.push'.length;
let closeIdx = -1;
for (; i < html.length; i++) {
  if (html[i] === '(') depth++;
  else if (html[i] === ')') { depth--; if (depth === 0) { closeIdx = i; break; } }
}

if (closeIdx === -1) { console.error('Could not find closing ) for last LOC.push'); process.exit(1); }

let endIdx = closeIdx + 1;
if (html[endIdx] === ';') endIdx++;
if (html[endIdx] === '\n') endIdx++;

html = html.slice(0, endIdx) + insertion + html.slice(endIdx);
fs.writeFileSync(filePath, html, 'utf8');

console.log('Done.');
console.log('портрет:', портретLocations.length);
console.log('дом:', домLocations.length);
console.log('дорога:', дорогаLocations.length);
console.log('город:', городLocations.length);
console.log('Total:', портретLocations.length + домLocations.length + дорогаLocations.length + городLocations.length);
